/*

 ARROWMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 36
   Tile set      : C:\Users\User\Documents\GitHub\GameBoy_Walkaround\maptextures.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define citymapWidth 40
#define citymapHeight 36
#define citymapBank 0

extern unsigned char citymap[];

/* End of ARROWMAP.H */
